cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    
]

naijabigstore/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('store.urls', namespace='store')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail(old).html
{% extends 'base.html' %}
{% load static %}
{% block title %}

{% endblock title %}

{% block content %}
<main>
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="cart-table-container">
                    <table class="table table-cart">
                        <thead>
                            <tr>
                                <th class="product-col">Product</th>
                                <th class="price-col">Price</th>
                                <th class="qty-col">Qty</th>
                                <th>Subtotal</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart %}
                            {% with product=item.product %}
                            <tr class="product-row">
                                <td class="product-col">
                                    <figure class="product-image-container">
                                        <a href="{{ product.get_absolute_url }}" class="product-image">
                                            <img src="{% if product.image %}{{ product.image.url}}{% else %}{% static 'img/no_image.png'%}
                                            {% endif %}" alt="product">
                                        </a>
                                    </figure>
                                    <h2 class="product-title">
                                        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                    </h2>
                                </td>
                                <td>$17.90</td>
                                <td>
                                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                        {{ item.update_quantity_form.quantity }}
                                        {{ item.update_quantity_form.override }}
                                        <input type="submit" class="btn btn-info" value="Update">
                                        {% csrf_token %}
                                    </form>
                                    <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                        <input type="submit" class="btn btn-danger" value="Remove">
                                        {% csrf_token %}
                                    </form>
                                </td>
                                <td>$17.90</td>
                            </tr>
                            {% endwith %}
                    {% endfor %}
                        </tbody>
    
                        <tfoot>
                            <tr>
                                <td colspan="4" class="clearfix">
                                    <div class="float-left">
                                        <a href="category.html" class="btn btn-outline-secondary">Continue Shopping</a>
                                    </div><!-- End .float-left -->
    
                                    <div class="float-right">
                                        <a href="#" class="btn btn-outline-secondary btn-clear-cart">Clear Shopping Cart</a>
                                        <a href="#" class="btn btn-outline-secondary btn-update-cart">Update Shopping
                                            Cart</a>
                                    </div><!-- End .float-right -->
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div><!-- End .cart-table-container -->
    
                <div class="cart-discount">
                    <h4>Apply Discount Code</h4>
                    <form action="#">
                        <div class="input-group">
                            <input type="text" class="form-control form-control-sm" placeholder="Enter discount code"
                                required>
                            <div class="input-group-append">
                                <button class="btn btn-sm btn-primary" type="submit">Apply Discount</button>
                            </div>
                        </div><!-- End .input-group -->
                    </form>
                </div><!-- End .cart-discount -->
            </div><!-- End .col-lg-8 -->
    
            <div class="col-lg-4">
                <div class="cart-summary">
                    <h3>Summary</h3>
    
                    <h4>
                        <a data-toggle="collapse" href="#total-estimate-section" class="collapsed" role="button"
                            aria-expanded="false" aria-controls="total-estimate-section">Estimate Shipping and Tax</a>
                    </h4>
    
                    <div class="collapse" id="total-estimate-section">
                        <form action="#">
                            <div class="form-group form-group-sm">
                                <label>Country</label>
                                <div class="select-custom">
                                    <select class="form-control form-control-sm">
                                        <option value="USA">United States</option>
                                        <option value="Turkey">Turkey</option>
                                        <option value="China">China</option>
                                        <option value="Germany">Germany</option>
                                    </select>
                                </div><!-- End .select-custom -->
                            </div><!-- End .form-group -->
    
                            <div class="form-group form-group-sm">
                                <label>State/Province</label>
                                <div class="select-custom">
                                    <select class="form-control form-control-sm">
                                        <option value="CA">California</option>
                                        <option value="TX">Texas</option>
                                    </select>
                                </div><!-- End .select-custom -->
                            </div><!-- End .form-group -->
    
                            <div class="form-group form-group-sm">
                                <label>Zip/Postal Code</label>
                                <input type="text" class="form-control form-control-sm">
                            </div><!-- End .form-group -->
    
                            <div class="form-group form-group-custom-control">
                                <label>Flat Way</label>
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="flat-rate">
                                    <label class="custom-control-label" for="flat-rate">Fixed $5.00</label>
                                </div><!-- End .custom-checkbox -->
                            </div><!-- End .form-group -->
    
                            <div class="form-group form-group-custom-control">
                                <label>Best Rate</label>
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="best-rate">
                                    <label class="custom-control-label" for="best-rate">Table Rate $15.00</label>
                                </div><!-- End .custom-checkbox -->
                            </div><!-- End .form-group -->
                        </form>
                    </div><!-- End #total-estimate-section -->
    
                    <table class="table table-totals">
                        <tbody>
                            <tr>
                                <td>Subtotal</td>
                                <td>$17.90</td>
                            </tr>
    
                            <tr>
                                <td>Tax</td>
                                <td>$0.00</td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td>Order Total</td>
                                <td>$17.90</td>
                            </tr>
                        </tfoot>
                    </table>
    
                    <div class="checkout-methods">
                        <a href="checkout-shipping.html" class="btn btn-block btn-sm btn-primary">Go to Checkout</a>
                        <a href="#" class="btn btn-link btn-block">Check Out with Multiple Addresses</a>
                    </div><!-- End .checkout-methods -->
                </div><!-- End .cart-summary -->
            </div><!-- End .col-lg-4 -->
        </div><!-- End .row -->
    </div><!-- End .container -->
    </main>
{% endblock content %}

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}
<style>
    table.cart>tbody>tr>td>a>img {
        width: 50px;
    }

    table.cart.table.table-hover thead,
    table.cart.table.table-hover tbody tr.total {
        background-color: lightblue;
    }

    select#id_quantity {
        padding: 8px;
    }
</style>
<div class="container mt-5">
    <h1>Your shopping cart</h1>

    <div class="row justify-content-center text-center">

        <div class="col-12">
            <div class="table-responsive">
                <table class="cart table table-hover">
                    <caption>Your shopping cart</caption>
                    <thead>
                        <tr>
                            <th scope="col">Image</th>
                            <th scope="col">Product</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Remove</th>
                            <th scope="col">Unit price</th>
                            <th scope="col">Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart %}
                        {% with product=item.product %}
                        <tr scope="row">
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.thumbnail %}{{ product.thumbnail.url}}{% else %}{% static 'assets/images/no_image.png'%}
                    {% endif %}">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.override }}
                                    <input type="submit" class="btn btn-outline-info rounded" value="Update">
                                    {% csrf_token %}
                                </form>
                            </td>
                            <td>
                                <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                    <input type="submit" class="btn btn-danger rounded" value="Remove">
                                    {% csrf_token %}
                                </form>
                            </td>
                            <td class="num">&#8358;{{ item.price }}</td>
                            <td class="num">&#8358;{{ item.total_price }}</td>
                        </tr>
                        {% endwith %}
                        {% endfor %}
                        <tr class="total">
                            <td>Total</td>
                            <td colspan="4"></td>
                            <td class="num">&#8358;{{ cart.get_total_price }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
    <div class="row justify-content-end">
        <p class="text-right">
            <a href="{% url 'store:product_list' %}" class="btn btn-light">Continue shopping</a>
            <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Checkout</a>
        </p>
    </div>
</div>





{% endblock %}